# Generated by Django 5.1.7 on 2025-05-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ano', models.PositiveIntegerField()),
                ('estudio', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
            ],
        ),
    ]
